In [36]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.svm import SVC

In [37]:
digits = load_digits()
model_1 = LogisticRegression()
model_2 = RandomForestClassifier()
model_3 = SVC()

In [38]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train , y_test = train_test_split(digits.data,digits.target,train_size=0.5)

In [54]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [58]:
for train_i , test_i in kf.split([9,8,2,5,4]):
    print(train_i,test_i)

[2 3 4] [0 1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


In [41]:
def get_score(model , x_train ,x_test, y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [42]:
get_score(model_1,x_train ,x_test, y_train,y_test)

/srv/conda/envs/notebook/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9543937708565072

In [43]:
get_score(model_2,x_train ,x_test, y_train,y_test)

0.949944382647386

In [44]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)

In [48]:
score_l= []
score_svm= []
score_rf= []
for train_i,test_i in kf.split(digits.data):
    X_train ,X_test, Y_train,Y_test = digits.data[train_i], digits.data[test_i], digits.target[train_i], digits.target[test_i]
    score_l.append(get_score(LogisticRegression(),X_train ,X_test, Y_train,Y_test))
    score_svm.append(get_score(SVC(),X_train ,X_test, Y_train,Y_test))
    score_rf.append(get_score(RandomForestClassifier(),X_train ,X_test, Y_train,Y_test))
    

/srv/conda/envs/notebook/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/srv/conda/envs/notebook/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logisti

In [50]:
print(score_l)
print(score_svm)
print(score_rf)

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
[0.9315525876460768, 0.9565943238731218, 0.9248747913188647]


In [59]:
x = digits.data
y = digits.target

In [70]:
from sklearn.model_selection import cross_val_score

In [71]:
cross_val_score(LogisticRegression(),x,y)

/srv/conda/envs/notebook/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/srv/conda/envs/notebook/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logisti

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [77]:
cross_val_score(SVC(C=100),x,y)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])

In [73]:
cross_val_score(RandomForestClassifier(),x,y)

array([0.93333333, 0.91388889, 0.95264624, 0.96657382, 0.92200557])